### ISSUE TITLE
Test Bug: Jquery trigger() method not working

### ISSUE THREAD

**Issue by v3rse** [infinum/learnQuery#2]
I've been working through the  `learnQuery` exercises. I, however, encountered an issue outlined in [this Stack Overflow question](http://stackoverflow.com/questions/37354637/jquery-trigger-works-only-for-one-event-specified-by-addeventlistener-at-a-time/37354773#37354773).

```
eventListener.on(selectedElement, 'click', methods.showLove);
eventListener.on(selectedElement, 'hover', methods.showLove);

$selectedElement.trigger('click');
$selectedElement.trigger('hover');
```

The Jquery trigger method used in the `eventListener.js` test spec doesn't trigger the `hover` event when using `addEventListener()` in my `on()` method. This causes the test to fail. Can someone confirm this?

**Comment by gabskoro** [comment]
Hi @v3rse,

Confirming that this doesn't work, probably because jQuery does something more than just dispatching the event, you can either use your `trigger` function or just create a new event and call the `dispatchEvent` ([mdn](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events)) function.

**Comment by dane-king** [comment]
So does the test need to change, if so should it be the selectedElement.trigger, instead of the $selectedElement, if so I would be happy to fix and submit a pull request
